-- Bronze table for deped_enrollment. Generated from config/ingestion/deped_enrollment.json:
--   python -m src.ingestion.cli ddl --source deped_enrollment
-- Do not edit by hand; tests/test_ingestion_pipeline.py fails if it differs.
--
-- Provenance columns first, then every publisher column of every schema
-- version as text. NULL means the column is not in that year's file; ''
-- means the publisher left it blank.
CREATE SCHEMA IF NOT EXISTS edu_access.`02-bronze`;
ALTER SCHEMA edu_access.`02-bronze` OWNER TO `reached-hq`;

CREATE TABLE IF NOT EXISTS edu_access.`02-bronze`.deped_enrollment_raw (
  `source_id` STRING NOT NULL,
  `source_system` STRING NOT NULL,
  `source_url` STRING NOT NULL,
  `school_year` STRING NOT NULL,
  `delivery_version` INT NOT NULL,
  `source_archive` STRING NOT NULL,
  `source_archive_sha256` STRING NOT NULL,
  `source_file` STRING NOT NULL,
  `source_sha256` STRING NOT NULL,
  `source_row_number` BIGINT NOT NULL,
  `schema_version` STRING NOT NULL,
  `schema_fingerprint` STRING NOT NULL,
  `batch_id` STRING NOT NULL,
  `run_id` STRING NOT NULL,
  `ingested_at_utc` TIMESTAMP NOT NULL,
  `code_revision` STRING NOT NULL,
  `school_id` STRING,
  `school_name` STRING,
  `region` STRING,
  `division` STRING,
  `province` STRING,
  `school_district` STRING,
  `legislative_district` STRING,
  `municipality` STRING,
  `barangay` STRING,
  `street_address` STRING,
  `sector` STRING,
  `school_management` STRING,
  `annex_status` STRING,
  `offers_es` STRING,
  `offers_jhs` STRING,
  `offers_shs` STRING,
  `kinder_male` STRING,
  `kinder_female` STRING,
  `g1_male` STRING,
  `g1_female` STRING,
  `g2_male` STRING,
  `g2_female` STRING,
  `g3_male` STRING,
  `g3_female` STRING,
  `g4_male` STRING,
  `g4_female` STRING,
  `g5_male` STRING,
  `g5_female` STRING,
  `g6_male` STRING,
  `g6_female` STRING,
  `esng_male` STRING,
  `esng_female` STRING,
  `g7_male` STRING,
  `g7_female` STRING,
  `g8_male` STRING,
  `g8_female` STRING,
  `g9_male` STRING,
  `g9_female` STRING,
  `g10_male` STRING,
  `g10_female` STRING,
  `jhsng_male` STRING,
  `jhsng_female` STRING,
  `g11_abm_male` STRING,
  `g11_abm_female` STRING,
  `g11_arts_male` STRING,
  `g11_arts_female` STRING,
  `g11_gas_male` STRING,
  `g11_gas_female` STRING,
  `g11_humss_male` STRING,
  `g11_humss_female` STRING,
  `g11_maritime_male` STRING,
  `g11_maritime_female` STRING,
  `g11_sports_male` STRING,
  `g11_sports_female` STRING,
  `g11_stem_male` STRING,
  `g11_stem_female` STRING,
  `g11_tvl_male` STRING,
  `g11_tvl_female` STRING,
  `g11_unique_male` STRING,
  `g11_unique_female` STRING,
  `g12_abm_male` STRING,
  `g12_abm_female` STRING,
  `g12_arts_male` STRING,
  `g12_arts_female` STRING,
  `g12_gas_male` STRING,
  `g12_gas_female` STRING,
  `g12_humss_male` STRING,
  `g12_humss_female` STRING,
  `g12_maritime_male` STRING,
  `g12_maritime_female` STRING,
  `g12_sports_male` STRING,
  `g12_sports_female` STRING,
  `g12_stem_male` STRING,
  `g12_stem_female` STRING,
  `g12_tvl_male` STRING,
  `g12_tvl_female` STRING,
  `g12_unique_male` STRING,
  `g12_unique_female` STRING,
  `Modified Curricular Offering Classification` STRING,
  `g11_sshs_acad_male` STRING,
  `g11_sshs_acad_female` STRING,
  `g11_sshs_techpro_male` STRING,
  `g11_sshs_techpro_female` STRING
)
USING DELTA
TBLPROPERTIES (
  'delta.columnMapping.mode' = 'name',
  'delta.minReaderVersion' = '2',
  'delta.minWriterVersion' = '5'
);

-- Owned by the team group, not by whoever ran the job first (D-009).
ALTER TABLE edu_access.`02-bronze`.deped_enrollment_raw OWNER TO `reached-hq`;
