-- Bronze table for deped_facilities. Generated from config/ingestion/deped_facilities.json:
--   python -m src.ingestion.cli ddl --source deped_facilities
-- Do not edit by hand; tests/test_ingestion_pipeline.py fails if it differs.
--
-- Provenance columns first, then every publisher column of every schema
-- version as text. NULL means the column is not in that year's file; ''
-- means the publisher left it blank.
CREATE SCHEMA IF NOT EXISTS edu_access.`02-bronze`;
ALTER SCHEMA edu_access.`02-bronze` OWNER TO `reached-hq`;

CREATE TABLE IF NOT EXISTS edu_access.`02-bronze`.deped_facilities_raw (
  `source_id` STRING NOT NULL,
  `source_system` STRING NOT NULL,
  `source_url` STRING NOT NULL,
  `school_year` STRING NOT NULL,
  `delivery_version` INT NOT NULL,
  `source_archive` STRING NOT NULL,
  `source_archive_sha256` STRING NOT NULL,
  `source_file` STRING NOT NULL,
  `source_sha256` STRING NOT NULL,
  `source_row_number` BIGINT NOT NULL,
  `schema_version` STRING NOT NULL,
  `schema_fingerprint` STRING NOT NULL,
  `batch_id` STRING NOT NULL,
  `run_id` STRING NOT NULL,
  `ingested_at_utc` TIMESTAMP NOT NULL,
  `code_revision` STRING NOT NULL,
  `school_id` STRING,
  `sector` STRING,
  `school_management` STRING,
  `offers_es` STRING,
  `offers_jhs` STRING,
  `offers_shs` STRING,
  `es_classrooms_instructional` STRING,
  `jhs_classrooms_instructional` STRING,
  `shs_classrooms_instructional` STRING,
  `es_classrooms_non_instructional` STRING,
  `jhs_classrooms_non_instructional` STRING,
  `shs_classrooms_non_instructional` STRING,
  `buildings_good_condition` STRING,
  `buildings_needs_minor_repair` STRING,
  `buildings_needs_major_repair` STRING,
  `buildings_for_completion` STRING,
  `buildings_ongoing_construction` STRING,
  `buildings_for_condemnation` STRING,
  `buildings_for_demolition` STRING,
  `es_temporary_learning_spaces` STRING,
  `hs_temporary_learning_spaces` STRING,
  `es_classes_using_temporary_learning_spaces` STRING,
  `hs_classes_using_temporary_learning_spaces` STRING,
  `es_makeshift_rooms` STRING,
  `hs_makeshift_rooms` STRING,
  `es_classes_using_makeshift_rooms` STRING,
  `hs_classes_using_makeshift_rooms` STRING,
  `es_has_covered_court` STRING,
  `hs_has_covered_court` STRING,
  `es_has_gymnasium` STRING,
  `hs_has_gymnasium` STRING,
  `es_has_gate_entrance` STRING,
  `hs_has_gate_entrance` STRING,
  `es_has_gate_exit` STRING,
  `hs_has_gate_exit` STRING,
  `es_has_perimeter_fence_permanent` STRING,
  `hs_has_perimeter_fence_permanent` STRING,
  `es_has_flood_marker` STRING,
  `hs_has_flood_marker` STRING,
  `es_has_perimeter_fence_temporary` STRING,
  `hs_has_perimeter_fence_temporary` STRING,
  `es_has_playground` STRING,
  `hs_has_playground` STRING,
  `es_has_garden` STRING,
  `hs_has_garden` STRING,
  `es_has_solar_panel` STRING,
  `hs_has_solar_panel` STRING,
  `es_has_bike_rack` STRING,
  `hs_has_bike_rack` STRING,
  `es_has_paved_pathway` STRING,
  `hs_has_paved_pathway` STRING,
  `es_has_pathway_roofing` STRING,
  `hs_has_pathway_roofing` STRING,
  `es_has_road_paved` STRING,
  `hs_has_road_paved` STRING,
  `es_has_road_unpaved` STRING,
  `hs_has_road_unpaved` STRING,
  `es_has_road_levelled` STRING,
  `hs_has_road_levelled` STRING,
  `es_has_road_rough` STRING,
  `hs_has_road_rough` STRING,
  `es_has_road_under_construction` STRING,
  `hs_has_road_under_construction` STRING,
  `es_accessible_private_4wheel` STRING,
  `hs_accessible_private_4wheel` STRING,
  `es_accessible_private_motorcycle` STRING,
  `hs_accessible_private_motorcycle` STRING,
  `es_accessible_boat` STRING,
  `hs_accessible_boat` STRING,
  `es_accessible_uv_express` STRING,
  `hs_accessible_uv_express` STRING,
  `es_accessible_pedicab` STRING,
  `hs_accessible_pedicab` STRING,
  `es_accessible_tricycle` STRING,
  `hs_accessible_tricycle` STRING,
  `es_accessible_jeepney` STRING,
  `hs_accessible_jeepney` STRING,
  `es_accessible_habalhabal` STRING,
  `hs_accessible_habalhabal` STRING,
  `es_accessible_train` STRING,
  `hs_accessible_train` STRING,
  `es_accessible_bus` STRING,
  `hs_accessible_bus` STRING,
  `es_accessible_bicycle` STRING,
  `hs_accessible_bicycle` STRING,
  `es_accessible_walking_hiking` STRING,
  `hs_accessible_walking_hiking` STRING
)
USING DELTA
TBLPROPERTIES (
  'delta.columnMapping.mode' = 'name',
  'delta.minReaderVersion' = '2',
  'delta.minWriterVersion' = '5'
);

-- Owned by the team group, not by whoever ran the job first (D-009).
ALTER TABLE edu_access.`02-bronze`.deped_facilities_raw OWNER TO `reached-hq`;
