"""The Silver data dictionary for a source, generated from its spec, so it cannot drift from the SQL."""

from src.silver.spec import (
    BOOLEAN, CATEGORY, COUNT, ENROLLMENT_STATUSES, FREE_TEXT, IDENTIFIER, QUARANTINE_REASONS,
)

LINEAGE_MEANING = {
    "batch_id": "The Bronze batch (one delivery of one school year) the row came from; joins `01-control`.ingestion_batches",
    "delivery_version": "Which delivery of the school year: 1, or 2+ after a publisher revision",
    "schema_version": "Which header the file had; tells a column absent that year (NULL) from a published blank (NULL)",
    "source_sha256": "SHA-256 of the publisher's CSV; with `source_row_number`, identifies the Bronze row exactly",
    "source_row_number": "The row's position in that CSV (data rows from 1)",
    "run_id": "The Silver run that built the row; every row of a build has the same one",
    "cleaned_at_utc": "When that Silver run built the table; one value per build, in UTC",
    "code_revision": "The commit that ran the build",
}

QUARANTINE_MEANING = {
    "school_id_blank": "`school_id` is NULL or blank",
    "school_id_malformed": "`school_id` is not exactly six digits",
    "school_id_duplicated": "the same `school_id` appears more than once in the school year; every copy is set aside",
    "count_negative": "a count is a negative whole number",
    "count_uncastable": "a count is not blank and not a whole number of at most nine digits (e.g. `5.0`, `abc`)",
}


def _absent_note(spec, name):
    versions = [v for v, names in spec.absent.items() if name in names]
    return f"; not in schema {', '.join(versions)} files, so NULL for those years" if versions else ""


def dictionary_markdown(spec):
    m = spec.mapping
    rows = []
    rows.append(("school_year", "STRING", "`school_year` (provenance)", "From the file names, as Bronze recorded it (key, with `school_id`)", "Never", ""))
    for c in spec.columns:
        source = f"`{c.source}`"
        absent = _absent_note(spec, c.name)
        if c.kind == IDENTIFIER:
            null = "Never (the gate fails otherwise)"
        elif c.kind == FREE_TEXT:
            null = "Published blank" + (" or a placeholder" if c.name in spec.placeholders else "") + absent
        elif c.kind == CATEGORY:
            null = "Published blank" + absent + " (an unmapped label fails the gate)"
        elif c.kind == BOOLEAN:
            null = "Published blank" + absent + " (an unmapped label fails the gate)"
        else:
            null = "Published blank" + absent + ". Never 0"
        rows.append((c.name, c.type.upper(), source, c.rule, null, c.finding))
    rows += [
        ("is_overseas", "BOOLEAN", "`sector`, `region`, `school_management`",
         "TRUE when any of them is `PSO` after mapping (Philippine Schools Overseas). Gold excludes these from geographic analysis",
         "Never", m["overseas"]["finding"]),
        ("enrollment_status", "STRING", "every count column",
         f"`{ENROLLMENT_STATUSES[0]}`: at least one count above 0; `{ENROLLMENT_STATUSES[1]}`: every published count is 0; "
         f"`{ENROLLMENT_STATUSES[2]}`: no count published at all. Flag only, rows are kept",
         "Never", "S-1"),
        ("barangay_possibly_truncated", "BOOLEAN", f"`{spec.barangay}`",
         f"TRUE when the published value is exactly {spec.barangay_cap} characters, the apparent cap; it may be cut off. Not repaired",
         "Never", m["barangay"]["finding"]),
    ]
    rows += [(name, kind.upper(), "provenance" if name not in ("run_id", "cleaned_at_utc", "code_revision") else "Silver run",
              LINEAGE_MEANING[name], "Never", "") for name, kind in spec.clean_columns() if name in LINEAGE_MEANING]

    lines = [
        f"# `{spec.clean_table}`: Silver data dictionary",
        "",
        f"Generated by `python -m src.silver.cli dictionary --source {spec.source_id}` from "
        f"[the Bronze contract](../../../config/ingestion/{spec.source_id}.json) and "
        f"[the Silver mapping](../../../config/mappings/{spec.source_id}.json). Do not edit by hand; "
        "`tests/test_silver.py` fails if it differs.",
        "",
        f"`` edu_access.`03-silver`.{spec.clean_table} ``: one row per school per school year, for the current "
        "delivery of each school year only (`01-control`.current_batches). Key: (`school_id`, `school_year`). "
        "Grade, sex, and strand stay as columns (the publisher's wide shape); unpivoting is a Gold decision. "
        "Every row names the Bronze row it came from (`source_sha256`, `source_row_number`), so the published "
        "value of any column can be read back from Bronze. Rules, counts, and the gate: "
        "[docs/operations/silver.md](../../operations/silver.md).",
        "",
        "**NULL** never means zero. A count column that a school year's file does not have is NULL too; "
        "`schema_version` tells the two apart" + "".join(
            f" (`{v}` lacks {', '.join(f'`{n}`' for n in names)})" for v, names in spec.absent.items()) + ".",
        "",
        "## Columns",
        "",
        "| Column | Type | Bronze source | Rule | NULL means | Finding |",
        "|---|---|---|---|---|---|",
    ]
    lines += [f"| `{name}` | {kind} | {source} | {rule} | {null} | {finding} |" for name, kind, source, rule, null, finding in rows]
    lines += [
        "",
        f"## `{spec.quarantine_table}`",
        "",
        "Rows that cannot be trusted, set aside rather than deleted. Every current Bronze row is in exactly one of "
        "the two tables. Read the published values from Bronze with `source_sha256` and `source_row_number`.",
        "",
        "| Column | Type | Meaning |",
        "|---|---|---|",
        "| `school_year` | STRING | As in the clean table |",
        f"| `{spec.identifier}` | STRING | As published, even if blank or malformed |",
        "| `quarantine_reasons` | `ARRAY<STRING>` | Every reason that applies, never empty (below) |",
    ]
    lines += [f"| `{name}` | {kind.upper()} | {LINEAGE_MEANING[name]} |"
              for name, kind in spec.quarantine_columns() if name in LINEAGE_MEANING]
    lines += ["", "| Reason | Meaning |", "|---|---|"]
    lines += [f"| `{r}` | {QUARANTINE_MEANING[r]} |" for r in QUARANTINE_REASONS]
    lines += ["", "## Renamed columns", "", "| Bronze column | Silver column | Why |", "|---|---|---|"]
    lines += [f"| `{src}` | `{r['to']}` | {r['reason']} |" for src, r in m.get("renames", {}).items()]
    lines += ["", "## Category labels", "",
              f"Published label (after whitespace is normalized) → standard value. The owner ({m['owner']}) approves a "
              "new label by a pull request to the mapping; until then the gate fails.", ""]
    for name, category in spec.categories.items():
        lines += [f"### `{name}` ({category.finding})", "", category.rule, "",
                  "| Published | Standard | Evidence |", "|---|---|---|"]
        evidence = {label["published"]: label["evidence"] for label in m["categories"][name]["labels"]}
        lines += [f"| `{published}` | `{standard}` | {evidence[published]} |"
                  for published, standard in category.labels.items()]
        lines.append("")
    lines += [f"### {', '.join(f'`{c}`' for c in m['booleans']['columns'])} ({m['booleans']['finding']})", "",
              f"{' and '.join(f'`{v}`' for v in spec.boolean_true)} → TRUE; "
              f"{' and '.join(f'`{v}`' for v in spec.boolean_false)} → FALSE; blank → NULL. {m['booleans']['evidence']}",
              "", "## Character repairs", "", "| Published | Repaired to | Evidence |", "|---|---|---|"]
    lines += [f"| `{r['published']}` | `{r['standard']}` | {r['evidence']} |" for r in m.get("character_repairs", [])]
    lines += ["", "## Placeholders set to NULL", "", "| Column | Values | Evidence |", "|---|---|---|"]
    lines += [f"| `{column}` | {', '.join(f'`{v}`' for v in entry['values'])} | {entry['evidence']} |"
              for column, entry in m.get("placeholders", {}).items()]
    lines.append("")
    return "\n".join(lines)
